# Generated by Django 4.2.2 on 2023-06-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blogpost_author_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
