# Generated by Django 4.2.2 on 2023-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mental_health', 'MENTAL HEALTH'), ('heart_disease', 'MENTAL DISEASE'), ('covid19', 'COVID 19'), ('immunization', 'IMMUNIZATION')], max_length=255),
        ),
    ]
